swagger: '2.0'
info:
  description: Api Activos Fijos - ASD
  version: '1.0'
  title: Api Activos Fijos - ASD
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8080'
basePath: /
tags:
  - name: empleado-controller
    description: Empleado Controller
  - name: activo-fijo-controller
    description: Activo Fijo Controller
  - name: area-controller
    description: Area Controller
paths:
  /api/v1/activos:
    get:
      tags:
        - activo-fijo-controller
      summary: getActivos
      operationId: getActivosUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/ActivoFijo'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - activo-fijo-controller
      summary: createActivo
      operationId: createActivoUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: activoFijo
          description: activoFijo
          required: true
          schema:
            $ref: '#/definitions/ActivoFijo'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ActivoFijo'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/api/v1/activos/fecha/{fechaCompra}':
    get:
      tags:
        - activo-fijo-controller
      summary: getActivoByFecha
      operationId: getActivoByFechaUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: fechaCompra
          in: path
          description: fechaCompra
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/api/v1/activos/serial/{serial}':
    get:
      tags:
        - activo-fijo-controller
      summary: getActivoBySerial
      operationId: getActivoBySerialUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: serial
          in: path
          description: serial
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/api/v1/activos/{id}':
    get:
      tags:
        - activo-fijo-controller
      summary: getActivoById
      operationId: getActivoByIdUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    put:
      tags:
        - activo-fijo-controller
      summary: updateActivo
      operationId: updateActivoUsingPUT
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int64
        - in: body
          name: activoUpdate
          description: activoUpdate
          required: true
          schema:
            $ref: '#/definitions/ActivoFijo'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ActivoFijo'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/api/v1/activos/{id}/{fechaCompra}/{serial}':
    get:
      tags:
        - activo-fijo-controller
      summary: getActivoByIdFechaSerial
      operationId: getActivoByIdFechaSerialUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int64
        - name: fechaCompra
          in: path
          description: fechaCompra
          required: true
          type: string
        - name: serial
          in: path
          description: serial
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/v1/areas:
    get:
      tags:
        - area-controller
      summary: getAreas
      operationId: getAreasUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Area'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/v1/personas:
    get:
      tags:
        - empleado-controller
      summary: getEmpleados
      operationId: getEmpleadosUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Empleado'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
definitions:
  ResponseEntity:
    type: object
    properties:
      body:
        type: object
      statusCode:
        type: string
        enum:
          - 100 CONTINUE
          - 101 SWITCHING_PROTOCOLS
          - 102 PROCESSING
          - 103 CHECKPOINT
          - 200 OK
          - 201 CREATED
          - 202 ACCEPTED
          - 203 NON_AUTHORITATIVE_INFORMATION
          - 204 NO_CONTENT
          - 205 RESET_CONTENT
          - 206 PARTIAL_CONTENT
          - 207 MULTI_STATUS
          - 208 ALREADY_REPORTED
          - 226 IM_USED
          - 300 MULTIPLE_CHOICES
          - 301 MOVED_PERMANENTLY
          - 302 FOUND
          - 302 MOVED_TEMPORARILY
          - 303 SEE_OTHER
          - 304 NOT_MODIFIED
          - 305 USE_PROXY
          - 307 TEMPORARY_REDIRECT
          - 308 PERMANENT_REDIRECT
          - 400 BAD_REQUEST
          - 401 UNAUTHORIZED
          - 402 PAYMENT_REQUIRED
          - 403 FORBIDDEN
          - 404 NOT_FOUND
          - 405 METHOD_NOT_ALLOWED
          - 406 NOT_ACCEPTABLE
          - 407 PROXY_AUTHENTICATION_REQUIRED
          - 408 REQUEST_TIMEOUT
          - 409 CONFLICT
          - 410 GONE
          - 411 LENGTH_REQUIRED
          - 412 PRECONDITION_FAILED
          - 413 PAYLOAD_TOO_LARGE
          - 413 REQUEST_ENTITY_TOO_LARGE
          - 414 URI_TOO_LONG
          - 414 REQUEST_URI_TOO_LONG
          - 415 UNSUPPORTED_MEDIA_TYPE
          - 416 REQUESTED_RANGE_NOT_SATISFIABLE
          - 417 EXPECTATION_FAILED
          - 418 I_AM_A_TEAPOT
          - 419 INSUFFICIENT_SPACE_ON_RESOURCE
          - 420 METHOD_FAILURE
          - 421 DESTINATION_LOCKED
          - 422 UNPROCESSABLE_ENTITY
          - 423 LOCKED
          - 424 FAILED_DEPENDENCY
          - 426 UPGRADE_REQUIRED
          - 428 PRECONDITION_REQUIRED
          - 429 TOO_MANY_REQUESTS
          - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
          - 451 UNAVAILABLE_FOR_LEGAL_REASONS
          - 500 INTERNAL_SERVER_ERROR
          - 501 NOT_IMPLEMENTED
          - 502 BAD_GATEWAY
          - 503 SERVICE_UNAVAILABLE
          - 504 GATEWAY_TIMEOUT
          - 505 HTTP_VERSION_NOT_SUPPORTED
          - 506 VARIANT_ALSO_NEGOTIATES
          - 507 INSUFFICIENT_STORAGE
          - 508 LOOP_DETECTED
          - 509 BANDWIDTH_LIMIT_EXCEEDED
          - 510 NOT_EXTENDED
          - 511 NETWORK_AUTHENTICATION_REQUIRED
      statusCodeValue:
        type: integer
        format: int32
  Area:
    type: object
    properties:
      codCiudad:
        type: string
      codigo:
        type: string
      descripcion:
        type: string
      id:
        type: integer
        format: int64
      nombre:
        type: string
  Empleado:
    type: object
    properties:
      id:
        type: integer
        format: int64
      idArea:
        type: integer
        format: int64
      numDocumento:
        type: string
      otrosNombres:
        type: string
      primerApellido:
        type: string
      primerNombre:
        type: string
      segundoApellido:
        type: string
      segundoNombre:
        type: string
      tipoDocumento:
        type: string
  ActivoFijo:
    type: object
    properties:
      alto:
        type: integer
        format: int64
      ancho:
        type: integer
        format: int64
      color:
        type: string
      descripcion:
        type: string
      estadoActual:
        type: string
      fechaBaja:
        type: string
        format: date-time
      fechaBajaAut:
        type: string
        format: date-time
      fechaCompra:
        type: string
        format: date-time
      id:
        type: integer
        format: int64
      largo:
        type: integer
        format: int64
      nombre:
        type: string
      numInventario:
        type: string
      peso:
        type: integer
        format: int64
      serial:
        type: string
      tipo:
        type: string
      valorCompra:
        type: integer
        format: int64
